version: '3'
services:
    app:
        container_name: api
        build: .
        ports: 
            - 8080:8080
        restart: on-failure
        #volumes:
        depends_on: 
            - postgres
        
    postgres:
        image: postgres:latest
        container_name: database
        environment: 
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - DATABASE_HOST=${DB_HOST}
        ports: 
            - 5432:5432
        volumes:
            - database_postgres:/var/lib/postgresql/data

volumes: 
    database_postgres:
